/* ===== Learn topics (part 1) ===== */
const TOPICS = [];
const T = (id, t, g, o) => { TOPICS.push({ id, t, g, ...o }); };
const Q = (q, o, a, e) => ({ q, o, a, e });

T('dbms-basics', 'DBMS Basics', 'Foundations', {
  what: 'A database management system (DBMS) is software that lets many users and programs define, store, query, update and protect a shared collection of related data (the database).',
  beg: 'Picture a school office with a very organised clerk. You ask, "Show me every student in CSE," and the clerk brings the answer without you opening a single drawer. The clerk is the DBMS, and the cabinet is the database.',
  why: 'Before databases, each program kept its own files. That caused duplicate data, inconsistent copies, awkward access to data, no protection when two users edited together, and weak security. A DBMS gives one controlled place for data with integrity rules, concurrency control, security and recovery.',
  how: ['Analyse the requirements and list the data to be kept.', 'Draw a conceptual model (ER or EER diagram).', 'Map the conceptual model to a logical model, usually relational tables.', 'Create the tables with SQL DDL (CREATE TABLE) and load data with DML (INSERT).', 'Query and update the data. The DBMS enforces keys, constraints and concurrent access.'],
  terms: [['Database', 'An organised collection of related data.'], ['Schema', 'The structure (design) of the database. It changes rarely.'], ['Instance', 'The data stored at one moment. It changes often.'], ['Data model', 'A set of concepts to describe data: ER, relational, and so on.'], ['DDL / DML', 'Data Definition Language creates structures; Data Manipulation Language reads and changes data.'], ['Data independence', 'Changing storage or one schema level without rewriting programs.']],
  real: 'A university database holds students, faculty, departments, courses and results. The registrar, the library and the exam cell all use the same data without keeping separate copies.',
  ex: { t: 'From requirement to database', steps: ['Requirement: "Track students and the departments they belong to."', 'Entities: STUDENT and DEPARTMENT.', 'Draw the ER diagram with a BELONGS_TO relationship.', 'Convert to tables STUDENT(Roll_No, Name, Dept_ID) and DEPARTMENT(Dept_ID, Name).', 'Write CREATE TABLE statements and load rows.'] },
  mist: ['Saying "database" when you mean the DBMS software (or the reverse).', 'Mixing up schema (design) and instance (current data).', 'Thinking a spreadsheet gives the same guarantees as a DBMS.'],
  exam: { defs: ['DBMS = software to create and manage databases.', 'Schema = description; instance = current contents.'], traps: ['"Schema changes often" is false; the instance changes often.'], short: ['List three problems of file-based systems.', 'Define data independence.'], long: ['Explain the three-schema architecture with a diagram.'], gate: ['Logical data independence means changing the conceptual schema without changing external views/programs.'], net: ['Know the roles of DBA, application programmers and end users.'] },
  quiz: [Q('Which describes the STRUCTURE of a database?', ['Instance', 'Schema', 'Query', 'Transaction'], 1, 'The schema is the structure. The instance is the data at a moment in time.'), Q('Which is a DDL statement?', ['SELECT', 'INSERT', 'CREATE TABLE', 'UPDATE'], 2, 'CREATE TABLE defines structure, so it is DDL.'), Q('Which problem does a DBMS reduce compared with plain files?', ['Redundancy and inconsistency', 'Need for storage', 'Need for keys', 'Need for users'], 0, 'Central control reduces duplicate and inconsistent data.')],
  sum: 'A DBMS provides controlled, shared, safe access to data. Design starts with a conceptual model, which is the subject of the next topics.', next: 'er-basics'
});
T('er-basics', 'ER Model Basics', 'Foundations', {
  what: 'The Entity–Relationship (ER) model describes data as entities (things), their attributes (properties) and relationships (associations) between entities. It is drawn as an ER diagram.',
  beg: 'Before building a house you draw a plan. An ER diagram is the plan for a database: boxes for things, ovals or lists for their details, and diamonds for how things are connected.',
  why: 'Tables are hard to discuss with non-technical users. A diagram is a shared picture that both users and designers can check before any table exists. Mistakes are cheap to fix on paper.',
  how: ['Find the nouns in the requirements: candidate entities.', 'List the properties of each: attributes. Choose a key.', 'Find the verbs that connect entities: relationships.', 'Decide cardinality (1:1, 1:N, M:N) and participation (total/partial).', 'Review the diagram with the users, then map it to tables.'],
  terms: [['Entity', 'A distinguishable thing of interest.'], ['Attribute', 'A property of an entity.'], ['Relationship', 'An association among entities.'], ['Cardinality', 'How many entities can be linked.'], ['Participation', 'Whether every entity must take part.']],
  viz: 'erbasic', real: 'Students enrol in courses. STUDENT and COURSE are entities. ENROLLS is a relationship with its own attribute, Grade.',
  ex: { t: 'Draw a small ER diagram', steps: ['Read: "Students enrol in courses and receive a grade."', 'Entities: STUDENT, COURSE.', 'Attributes: Roll_No, Name, Email; Course_ID, Title, Credits.', 'Relationship: ENROLLS, M:N, with attribute Grade.', 'Mark keys: Roll_No and Course_ID.'] },
  mist: ['Turning every noun into an entity when it is only an attribute (for example Name).', 'Forgetting to choose a key.', 'Drawing a relationship without deciding its cardinality.'],
  exam: { defs: ['ER model was proposed by Peter Chen (1976).', 'Entity set = collection of similar entities.'], traps: ['A relationship can have attributes; an attribute cannot have relationships.'], short: ['What are the components of an ER diagram?'], long: ['Design an ER diagram for a library and list all assumptions.'], gate: ['Relationship attributes of M:N relationships cannot be moved to either entity.'], net: ['Know Chen, crow\'s foot and UML notations exist.'] },
  quiz: [Q('In an ER diagram a diamond represents:', ['Entity', 'Attribute', 'Relationship', 'Key'], 2, 'Diamonds are relationships.'), Q('The ER model is used mainly at which stage?', ['Physical design', 'Conceptual design', 'Backup', 'Query tuning'], 1, 'ER modelling is conceptual design.'), Q('Which is best modelled as an attribute of STUDENT?', ['Course', 'Department', 'Email', 'Faculty'], 2, 'Email is a simple property. Course and Department are things with details of their own.')],
  sum: 'ER modelling turns requirements into entities, attributes and relationships before any table is built.', next: 'entity'
});
T('entity', 'Entity', 'ER Model', {
  what: 'An entity is a real-world thing that can be told apart from other things and about which we store data. An entity set (entity type) is a collection of entities of the same kind.',
  beg: 'Your friend Asha is one entity. "Students" is the entity set. In the diagram we draw the set once, as a rectangle called STUDENT.',
  why: 'Entities are the nouns of the database. Getting them right decides the table structure later.',
  how: ['Look for things that need to be remembered and that have several properties.', 'Give each entity a singular, clear name.', 'Check that each entity can be told apart from others (it needs a key).', 'Separate entity sets that behave differently.'],
  terms: [['Entity', 'One individual thing.'], ['Entity type / set', 'The collection of all similar entities.'], ['Strong entity', 'Has its own key.'], ['Weak entity', 'Needs another entity to be identified.']],
  viz: 'erbasic', real: 'A hospital has entities PATIENT, DOCTOR, WARD and APPOINTMENT.',
  ex: { t: 'Choosing entities', steps: ['Text: "Each book has an ISBN and a title. Members borrow books."', 'Nouns: book, ISBN, title, member.', 'ISBN and title are properties, so they are attributes.', 'BOOK and MEMBER are entities.'] },
  mist: ['Using plural names such as STUDENTS.', 'Making a property (like Colour) its own entity when no details are needed.'],
  exam: { defs: ['Entity = object with independent existence (strong).'], traps: ['An entity type is not one row; it is the whole set.'], short: ['Differentiate entity and entity set.'], long: ['Explain strong and weak entity sets with examples.'], gate: ['An entity set without a key of its own is a weak entity set.'], net: ['Entity vs object in OOP.'] },
  quiz: [Q('The collection of all STUDENT entities is called:', ['Attribute', 'Entity set', 'Relationship', 'Key'], 1, 'A collection of similar entities is an entity set.'), Q('In a diagram an entity is usually a:', ['Rectangle', 'Diamond', 'Circle', 'Triangle'], 0, 'Entities are rectangles.'), Q('Which is more likely an entity than an attribute?', ['Colour', 'Department', 'Age', 'Phone'], 1, 'A department has details of its own, so it is an entity.')],
  sum: 'Entities are the things you store data about. Choose them carefully and name them clearly.', next: 'attributes'
});
T('attributes', 'Attributes', 'ER Model', {
  what: 'An attribute is a property that describes an entity or a relationship. Each attribute has a domain (the set of allowed values).',
  beg: 'A student card shows Name, Roll number and Date of birth. Each of these is an attribute.',
  why: 'Attributes carry the actual facts. Their kinds (simple, composite, multi-valued, derived) decide how tables are built.',
  how: ['List the facts you need about each entity.', 'Mark composite attributes (Address = Street + City).', 'Mark multi-valued attributes (Phones).', 'Mark derived attributes (Age from DOB).', 'Choose the key attribute(s).'],
  terms: [['Simple', 'Cannot be split.'], ['Composite', 'Made of parts, such as Name = First + Last.'], ['Single-valued', 'One value per entity.'], ['Multi-valued', 'Several values, such as Phones.'], ['Derived', 'Computed from others, such as Age.'], ['NULL', 'Unknown or not applicable.']],
  viz: 'student', real: 'STUDENT: Roll_No (key), Name (composite), Phones (multi-valued), Age (derived from DOB).',
  ex: { t: 'Mapping attribute kinds to tables', steps: ['Simple attribute: one column.', 'Composite: one column per part.', 'Multi-valued: a separate table with the entity key.', 'Derived: usually not stored; computed in queries.'] },
  mist: ['Storing Age instead of Date_of_birth.', 'Keeping several phone numbers in one text column.'],
  exam: { defs: ['Derived attribute is drawn with a dashed oval.', 'Multi-valued is drawn with a double oval.'], traps: ['A key attribute is underlined; a partial key is underlined with a dashed line.'], short: ['List the types of attributes with examples.'], long: ['How are multi-valued attributes mapped to relations?'], gate: ['Multi-valued attribute → separate relation containing the entity key and the attribute.'], net: ['Domain vs data type.'] },
  quiz: [Q('Age computed from Date_of_birth is a:', ['Simple attribute', 'Derived attribute', 'Key attribute', 'Multi-valued attribute'], 1, 'It can be calculated, so it is derived.'), Q('Multiple phone numbers per student make Phone:', ['Composite', 'Derived', 'Multi-valued', 'Weak'], 2, 'Several values for one entity is multi-valued.'), Q('Address split into Street, City, Pin is:', ['Composite', 'Derived', 'Multi-valued', 'Key'], 0, 'It has sub-parts, so it is composite.')],
  sum: 'Attributes describe entities. Their kind (simple, composite, multi-valued, derived) tells you how to store them.', next: 'keys'
});
T('keys', 'Keys', 'ER Model', {
  what: 'A key is a set of attributes that identifies each entity (or row) uniquely. A primary key is the candidate key chosen as the main identifier.',
  beg: 'Two students may share a name, but the roll number is different for each. The roll number works like a passport number: it points to exactly one person.',
  why: 'Without keys, you cannot say which row you mean, cannot link tables, and cannot prevent duplicates.',
  how: ['Find all sets of attributes that are unique: superkeys.', 'Keep the minimal ones: candidate keys.', 'Choose one as the primary key. The others are alternate keys.', 'In another table, a foreign key holds a primary key value to point at a row.'],
  terms: [['Superkey', 'Any set that identifies rows uniquely.'], ['Candidate key', 'A minimal superkey.'], ['Primary key', 'The chosen candidate key. It cannot be NULL.'], ['Foreign key', 'Refers to a key in another table.'], ['Composite key', 'A key with several attributes.'], ['Partial key', 'Identifies a weak entity only within its owner.']],
  viz: 'erbasic', real: 'Roll_No is the primary key of STUDENT. Email could be an alternate key. In ENROLLS, (Roll_No, Course_ID) is a composite key.',
  ex: { t: 'Finding keys', steps: ['STUDENT(Roll_No, Email, Name, Phone).', 'Roll_No and Email are each unique → candidate keys.', 'Choose Roll_No as the primary key.', 'Email becomes an alternate key (UNIQUE).', '{Roll_No, Name} is a superkey, but not minimal.'] },
  mist: ['Calling every unique set a candidate key (it must be minimal).', 'Allowing NULL in a primary key.'],
  exam: { defs: ['Every candidate key is a superkey; not every superkey is a candidate key.'], traps: ['A table can have many candidate keys but only one primary key.'], short: ['Differentiate candidate and primary key.'], long: ['Explain all types of keys with examples.'], gate: ['Counting candidate keys or superkeys of a relation with given functional dependencies is a common pattern.'], net: ['Foreign key referential integrity rules.'] },
  quiz: [Q('A minimal superkey is a:', ['Foreign key', 'Candidate key', 'Composite attribute', 'Weak key'], 1, 'Minimal superkeys are candidate keys.'), Q('Which key may NOT contain NULL?', ['Primary key', 'Foreign key', 'Alternate key', 'None'], 0, 'Primary keys must be non-null.'), Q('A foreign key refers to:', ['A key in the same row only', 'A key in another (or the same) table', 'A derived attribute', 'A view'], 1, 'It points to a key in another table or the same table.')],
  sum: 'Keys identify rows. Primary keys identify; foreign keys connect.', next: 'relationships'
});
T('relationships', 'Relationships', 'ER Model', {
  what: 'A relationship is an association among two or more entities. A relationship set groups similar relationships. The number of entity types in it is its degree (binary = 2).',
  beg: '"Priya enrols in DBMS" links a student and a course. ENROLLS is the relationship.',
  why: 'Entities alone are isolated. Relationships describe how data is connected, and they become foreign keys or link tables.',
  how: ['Find verbs between entities.', 'Name each relationship with a verb phrase.', 'Decide degree (binary, ternary).', 'Add relationship attributes such as Grade or Visit_Date.', 'Set cardinality and participation.'],
  terms: [['Degree', 'Number of participating entity types.'], ['Role', 'The part an entity plays; used in recursive relationships.'], ['Recursive', 'An entity type related to itself (Employee supervises Employee).'], ['Identifying', 'Links a weak entity to its owner.']],
  viz: 'erbasic', real: 'DOCTOR treats PATIENT is many-to-many. The date of a visit belongs to the relationship, not to either entity.',
  ex: { t: 'Model ENROLLS', steps: ['Entities: STUDENT and COURSE.', 'Verb: "enrols".', 'A student takes many courses, and a course has many students → M:N.', 'Grade depends on both → relationship attribute.', 'Later, ENROLLS becomes its own table.'] },
  mist: ['Putting Grade on STUDENT or COURSE.', 'Using a noun as the relationship name.'],
  exam: { defs: ['Degree of a relationship = number of participating entity sets.'], traps: ['A ternary relationship is not always equal to three binary ones.'], short: ['What is a recursive relationship?'], long: ['Explain degree and cardinality with examples.'], gate: ['Relationship attribute for M:N must be stored in the relationship table.'], net: ['Unary, binary, ternary relationships.'] },
  quiz: [Q('The degree of ENROLLS(STUDENT, COURSE) is:', ['1', '2', '3', '4'], 1, 'Two entity types → binary → degree 2.'), Q('EMPLOYEE supervises EMPLOYEE is:', ['Ternary', 'Recursive', 'Weak', 'Derived'], 1, 'An entity set related to itself is recursive.'), Q('Grade in ENROLLS belongs to:', ['STUDENT', 'COURSE', 'The relationship', 'Neither'], 2, 'It depends on the pair, so it is a relationship attribute.')],
  sum: 'Relationships link entities and can carry attributes.', next: 'cardinality'
});
T('cardinality', 'Cardinality', 'ER Model', {
  what: 'Cardinality (mapping cardinality) is the number of entities from one set that can be associated with entities of another set: 1:1, 1:N, N:1 or M:N.',
  beg: 'One mother has many children (1:N). One child has one mother. Students and courses: each student takes many courses and each course has many students (M:N).',
  why: 'Cardinality tells you where the foreign key goes, or whether you need a separate table.',
  how: ['For each side, ask: how many partners can one entity have? (one or many)', 'Combine the answers into 1:1, 1:N, N:1 or M:N.', 'Mark 1 and N next to the entities.', 'Use it in mapping: 1:N → key on N side; M:N → new table.'],
  terms: [['1:1', 'At most one on each side.'], ['1:N', 'One on one side, many on the other.'], ['M:N', 'Many on both sides.'], ['(min,max)', 'Notation giving lower and upper limits.']],
  viz: 'university', real: 'DEPARTMENT 1 — N STUDENT means each student belongs to one department, and a department has many students.',
  ex: { t: 'Read the cardinality', steps: ['Ask "How many departments can a student belong to?" → one.', 'Ask "How many students can a department have?" → many.', 'Result: STUDENT N : 1 DEPARTMENT.', 'The foreign key Dept_ID goes into STUDENT.'] },
  mist: ['Reading the label on the wrong side.', 'Forgetting that M:N needs a separate table.'],
  exam: { defs: ['Cardinality ratio ∈ {1:1, 1:N, N:1, M:N}.'], traps: ['The N sits next to the entity that can appear many times.'], short: ['Give one example for each cardinality.'], long: ['How does cardinality decide relational mapping?'], gate: ['Minimum tables for an ER diagram: one per entity plus one per M:N relationship (1:1 and 1:N merge into entity tables).'], net: ['Cardinality vs degree.'] },
  quiz: [Q('Which needs a separate table when mapped?', ['1:1', '1:N', 'M:N', 'Recursive 1:1'], 2, 'M:N needs a table of its own.'), Q('In a 1:N relationship, where does the foreign key go?', ['1 side', 'N side', 'Both', 'Neither'], 1, 'On the N (many) side.'), Q('A person has one passport and a passport belongs to one person:', ['1:1', '1:N', 'M:N', 'N:1'], 0, 'One on each side is 1:1.')],
  sum: 'Cardinality counts partners per side and drives mapping.', next: 'participation'
});
T('participation', 'Participation Constraints', 'ER Model', {
  what: 'Participation says whether every entity of a set must take part in a relationship. Total (mandatory, double line) means every entity participates. Partial (optional, single line) means some may not.',
  beg: 'Every account must have an owner (total). A customer might not have any account yet (partial).',
  why: 'Participation turns business rules into checks: NOT NULL foreign keys, or required rows.',
  how: ['Ask: "Can an entity exist without this relationship?"', 'If not → total. If yes → partial.', 'Draw a double line for total.', 'In mapping, total on the foreign-key side means NOT NULL.'],
  terms: [['Total', 'Also called existence dependency or mandatory.'], ['Partial', 'Optional.'], ['Existence dependency', 'An entity cannot exist without another.']],
  viz: 'account', real: 'Every ACCOUNT must be OWNED by a CUSTOMER (total). A CUSTOMER may have none (partial).',
  ex: { t: 'Decide participation', steps: ['Rule: "Every student belongs to a department."', 'STUDENT participation in BELONGS_TO is total.', 'Rule: "Departments may have no students yet."', 'DEPARTMENT participation is partial.', 'Mapping: Dept_ID in STUDENT is NOT NULL.'] },
  mist: ['Confusing total participation with cardinality.', 'Marking everything total.'],
  exam: { defs: ['Total participation = double line from entity to relationship.'], traps: ['Participation (min) and cardinality (max) are different ideas.'], short: ['Explain total and partial participation.'], long: ['How is total participation enforced in relational tables?'], gate: ['Weak entity always participates totally in its identifying relationship.'], net: ['(min,max) notation.'] },
  quiz: [Q('Double line from an entity to a relationship means:', ['Partial', 'Total', 'Weak', 'Derived'], 1, 'Double line = total participation.'), Q('Total participation on the FK side usually gives:', ['NULL allowed', 'NOT NULL FK', 'No FK', 'A new table'], 1, 'Every row must have a value.'), Q('Participation constraint is also called:', ['Cardinality ratio', 'Existence dependency', 'Domain', 'Key'], 1, 'Total participation is an existence dependency.')],
  sum: 'Participation states whether taking part is mandatory or optional.', next: 'weak-entity'
});
T('weak-entity', 'Weak Entity', 'ER Model', {
  what: 'A weak entity has no key of its own. It is identified by combining the key of an owner (identifying) entity with its own partial key. It is drawn with double borders and linked by a double diamond.',
  beg: 'A dependent (child) of an employee may share a first name with another employee\'s child. The child is identified only "under" an employee: employee 7 → child "Asha".',
  why: 'Some things exist only as parts of others. Modelling them as weak entities prevents orphans and keeps keys honest.',
  how: ['Notice an entity whose key is not unique on its own.', 'Identify its owner entity.', 'Draw the identifying relationship (double diamond).', 'Mark the partial key (dashed underline).', 'Map: key = owner key + partial key, with a foreign key to the owner.'],
  terms: [['Owner / identifying entity', 'The strong entity it depends on.'], ['Partial key (discriminator)', 'Distinguishes weak entities of the same owner.'], ['Identifying relationship', 'Links owner and weak entity.']],
  viz: 'weak', real: 'DEPENDENT(Dep_Name, Relationship) of EMPLOYEE. Key = (Emp_ID, Dep_Name).',
  ex: { t: 'Map a weak entity', steps: ['EMPLOYEE(Emp_ID, Name).', 'DEPENDENT has partial key Dep_Name.', 'Table DEPENDENT(Emp_ID, Dep_Name, Relationship, Birth_Date).', 'PRIMARY KEY (Emp_ID, Dep_Name).', 'FOREIGN KEY (Emp_ID) references EMPLOYEE.'] },
  mist: ['Giving a weak entity its own independent key.', 'Forgetting the total participation of the weak entity.'],
  exam: { defs: ['Weak entity: double rectangle; identifying relationship: double diamond.'], traps: ['A weak entity has a partial key, not "no key at all".'], short: ['What is a weak entity? Give an example.'], long: ['Map a weak entity set to relations.'], gate: ['Weak entity relation key = owner PK ∪ partial key.'], net: ['Existence and identification dependency.'] },
  quiz: [Q('A weak entity is identified by:', ['Its own primary key', 'Owner key + partial key', 'A foreign key alone', 'Nothing'], 1, 'Owner key plus partial key.'), Q('Identifying relationship is drawn as a:', ['Double diamond', 'Dashed oval', 'Triangle', 'Circle'], 0, 'Double diamond.'), Q('Participation of a weak entity in its identifying relationship is:', ['Partial', 'Total', 'Optional', 'None'], 1, 'It cannot exist without the owner, so total.')],
  sum: 'A weak entity borrows part of its identity from its owner.', next: 'eer-model'
});
T('eer-model', 'EER Model', 'EER Core', {
  what: 'The Enhanced (Extended) ER model adds superclass/subclass, specialization, generalization, constraints on them, attribute and relationship inheritance, and aggregation/categories to the basic ER model.',
  beg: 'A basic ER diagram treats "employee" as one flat box. In real life managers, engineers and clerks share many facts but also differ. EER lets you draw both what they share and how they differ.',
  why: 'Without EER, you either repeat common attributes in many entities, or you cram optional attributes (mostly NULL) into one entity. EER captures "is-a" structure cleanly.',
  how: ['Start with a basic ER model.', 'Spot entities with shared attributes (generalize) or with subgroups having their own attributes (specialize).', 'Draw superclass, subclasses and the ISA circle.', 'Add constraints: disjoint/overlapping and total/partial.', 'Map to tables using one of four standard options.'],
  terms: [['Superclass', 'The general entity type.'], ['Subclass', 'A more specific subgroup.'], ['ISA', 'The "is-a" link between them.'], ['Inheritance', 'Subclass gets attributes and relationships of its superclass.'], ['Constraints', 'Disjoint/overlapping; total/partial.']],
  viz: 'person', real: 'PERSON specialized into STUDENT and FACULTY, each with its own attributes.',
  ex: { t: 'From ER to EER', steps: ['ER: separate STUDENT and FACULTY boxes, each with Name, Address, Phone.', 'Notice duplication.', 'Create PERSON with the common attributes.', 'Link STUDENT and FACULTY to PERSON with an ISA circle.', 'Add the constraints d/o and total/partial.'] },
  mist: ['Using EER only to show off; not every entity needs subclasses.', 'Forgetting constraints on the ISA.'],
  exam: { defs: ['EER = ER + specialization/generalization + aggregation + categories (union types).'], traps: ['Aggregation is different from generalization.'], short: ['List the features added by EER.'], long: ['Explain EER with a diagram and map it to relations.'], gate: ['Attribute inheritance: subclass has its own + inherited attributes.'], net: ['Specialization lattice vs hierarchy.'] },
  quiz: [Q('EER extends ER mainly with:', ['Normalization', 'Superclass/subclass and specialization', 'SQL views', 'Indexes'], 1, 'Superclass/subclass concepts are central.'), Q('Which is NOT part of EER?', ['Generalization', 'Specialization', 'Aggregation', 'Query optimizer'], 3, 'The optimizer is a DBMS component.'), Q('The ISA symbol expresses:', ['is-a', 'has-a', 'part-of', 'owns'], 0, 'ISA = is-a.')],
  sum: 'EER adds the is-a hierarchy to ER. The rest of this path explores it in depth.', next: 'generalization'
});
T('generalization', 'Generalization', 'EER Core', {
  what: 'Generalization is a bottom-up process: you combine two or more entity types that share attributes into a higher-level entity type (the superclass) and move the common attributes up to it. The original entity types become subclasses that keep only their specific attributes.',
  beg: 'You have STUDENT with Name/Address/Phone/CGPA and FACULTY with Name/Address/Phone/Salary. The first three columns repeat. Move them into PERSON. Now STUDENT is "a person who also has CGPA".',
  why: 'It removes duplication, gives a single place to change common attributes, lets you attach shared relationships once, and states the real-world "is-a" fact in the model.',
  how: ['Start with separate entity types.', 'Find attributes with the same meaning across them (common attributes).', 'Create a superclass and choose its key.', 'Move the common attributes up. Keep specific ones in the subclasses.', 'Connect superclass and subclasses with ISA and decide the constraints.'],
  terms: [['Bottom-up', 'Start from specifics and abstract upward.'], ['Superclass', 'Result of generalization.'], ['Common attributes', 'Attributes that mean the same in all subclasses.'], ['Specific attributes', 'Stay with the subclass.']],
  widget: 'gen', pipe: 'person', real: 'STUDENT, FACULTY and EMPLOYEE generalize to PERSON. CAR and TRUCK generalize to VEHICLE. SAVINGS and CURRENT generalize to ACCOUNT.',
  ex: { t: 'Generalize STUDENT and FACULTY (10 steps)', steps: ['Problem: a university has STUDENT and FACULTY. Both have Name, Address and Phone.', 'Identify entities: STUDENT(Student_ID, Name, Address, Phone, CGPA) and FACULTY(Faculty_ID, Name, Address, Phone, Salary).', 'Identify common attributes: Name, Address, Phone (and an ID).', 'Identify the superclass: PERSON with Person_ID, Name, Address, Phone.', 'Identify subclasses: STUDENT keeps CGPA; FACULTY keeps Salary.', 'Create ISA from the two subclasses to PERSON.', 'Decide total or partial: other people (visitors) exist → partial.', 'Decide disjoint or overlapping: a student cannot be faculty here → disjoint.', 'Generate the EER diagram and convert to tables: PERSON, STUDENT, FACULTY.', 'Generate SQL with STUDENT.person_id as PRIMARY KEY and FOREIGN KEY to PERSON.'] },
  mist: ['Creating the superclass but leaving duplicate common attributes in subclasses.', 'Generalizing entities that only share a name, not a meaning.', 'Confusing generalization with specialization (direction).', 'Keeping separate keys in the subclasses instead of inheriting the superclass key.'],
  exam: { defs: ['Generalization: bottom-up; combining entities into a higher-level entity.', 'Also called abstraction: hides differences, shows commonality.'], freq: ['Direction of generalization', 'Attributes that move to the superclass', 'Relation between generalization and specialization'], traps: ['"Generalization is top-down" is false.', 'Specific attributes are NOT moved to the superclass.'], pat: ['"Which process combines entity types into a super type?"', '"Bottom-up refinement is called …"'], short: ['Define generalization with an example.', 'Why is generalization used?'], long: ['Explain generalization with an EER diagram and map it to relational tables.'], gate: ['Generalization removes attribute redundancy by pulling common attributes into a superclass.'], net: ['Generalization is one of the abstraction mechanisms (with aggregation and classification).'], univ: ['Draw an EER diagram showing generalization of two entity types.'] },
  quiz: [Q('Generalization is best described as:', ['Top-down splitting of an entity', 'Bottom-up combining of entities with common attributes', 'Deleting entities', 'Adding indexes'], 1, 'Generalization builds a superclass from similar entities, bottom-up.'), Q('After generalizing STUDENT and FACULTY into PERSON, where does CGPA stay?', ['PERSON', 'STUDENT', 'FACULTY', 'It is deleted'], 1, 'Specific attributes stay with the subclass.'), Q('What is the main benefit?', ['Faster CPU', 'Less duplication of common attributes', 'More NULLs', 'Bigger diagrams'], 1, 'Common attributes are stored once.'), Q('Which pair is a good candidate for generalization?', ['CAR and BIKE (RegNo, Make, Year)', 'STUDENT and BOOK', 'CITY and SALARY', 'ROOM and TIME'], 0, 'CAR and BIKE share real, same-meaning attributes.')],
  sum: 'Generalization = bottom-up: extract common attributes into a superclass. Subclasses keep only what is specific.', next: 'specialization'
});
T('specialization', 'Specialization', 'EER Core', {
  what: 'Specialization is a top-down process: you take an entity type and define subclasses (subgroups) that have extra attributes or relationships of their own, or that need to be distinguished for some reason.',
  beg: 'EMPLOYEE is a box with Name and Salary. But only managers get a Bonus and only engineers have a Specialty. Instead of leaving Bonus empty for most employees, create MANAGER and ENGINEER as subclasses.',
  why: 'It avoids attributes that are mostly NULL and lets you attach relationships to the subgroup they really belong to (only MANAGER manages a DEPARTMENT).',
  how: ['Start with one entity type.', 'Look for subgroups that differ: extra attributes, extra relationships, different rules.', 'Define a subclass for each. Give it only its specific attributes.', 'Connect to the superclass with ISA.', 'Set disjoint/overlapping and total/partial.'],
  terms: [['Top-down', 'Start general and refine.'], ['Defining attribute', 'A value of an attribute decides the subclass (JobType = "Engineer"). Called attribute-defined.'], ['User-defined', 'Users assign entities to subclasses manually.'], ['Specialization hierarchy / lattice', 'Multiple levels; a lattice allows a subclass with several superclasses.']],
  widget: 'gen', pipe: 'person3', real: 'PERSON specialized into STUDENT, FACULTY and STAFF. EMPLOYEE into MANAGER and ENGINEER.',
  ex: { t: 'Specialize PERSON', steps: ['Start: PERSON(Person_ID, Name, Address).', 'Notice three groups with different data: students, faculty, staff.', 'Define STUDENT(CGPA), FACULTY(Salary), STAFF(Grade).', 'Draw the ISA circle under PERSON.', 'Persons who are none of these exist → partial.', 'A person is one of them at most → disjoint.'] },
  mist: ['Specializing when subclasses have no extra attributes or relationships.', 'Repeating superclass attributes in subclasses.', 'Forgetting the ISA constraints.'],
  exam: { defs: ['Specialization: top-down; defines subclasses of an entity type.', 'Each subclass member is also a member of the superclass.'], freq: ['Attribute-defined vs user-defined', 'Specialization vs generalization'], traps: ['Specialization does not create new entities; it categorizes existing ones.'], pat: ['"The process of defining subclasses is …"'], short: ['Define specialization with an example.', 'What are the reasons for specialization?'], long: ['Explain specialization, its constraints and mapping to relations.'], gate: ['A subclass entity inherits all attributes and relationships of its superclass.'], net: ['Top-down design: specialization; bottom-up: generalization.'], univ: ['Draw an EER for EMPLOYEE specialized into SECRETARY, TECHNICIAN and ENGINEER.'] },
  quiz: [Q('Specialization is:', ['Bottom-up', 'Top-down', 'Sideways', 'Random'], 1, 'Specialization refines an entity into subclasses, top-down.'), Q('Why specialize EMPLOYEE into MANAGER?', ['Managers have attributes/relationships others do not', 'To create NULLs', 'To remove keys', 'To slow queries'], 0, 'Specific attributes and relationships belong with the subgroup.'), Q('A user decides membership of each entity in a subclass. This is:', ['Attribute-defined', 'User-defined', 'Total', 'Derived'], 1, 'Manual assignment is user-defined specialization.')],
  sum: 'Specialization = top-down: define subclasses for subgroups with distinct attributes or relationships.', next: 'super-sub'
});
