/* ===== Practice, quiz engine, AI quiz, competitive, progress, leaderboard, admin, help, search ===== */
const TYPES_P = { identify: 'Identify entities / attributes', genspec: 'Generalization & specialization', constraint: 'Constraints (d/o, total/partial)', mapping: 'Mapping options', table: 'Table mapping', sql: 'SQL mapping', diagram: 'Diagram interpretation' };
const PF = { type: '', topic: '', d: '' }; let PS = null;
const topicOpts = (sel, all = 'All topics') => `<option value="">${all}</option>` + GROUPS.map(g => `<optgroup label="${g}">${TOPICS.filter(t => t.g === g).map(t => `<option value="${t.id}" ${sel === t.id ? 'selected' : ''}>${esc(t.t)}</option>`).join('')}</optgroup>`).join('');
const filtered = () => PRACTICE.filter(p => (!PF.type || p.type === PF.type) && (!PF.topic || p.topic === PF.topic) && (!PF.d || p.d === PF.d));
const acc = (n, ok) => n ? Math.round(100 * ok / n) : null;

/* ---------- Practice ---------- */
VIEWS.practice = topic => {
  if (topic && topicById(topic) && PF.topic !== topic) { PF.topic = topic; }
  if (PS && !PS.done) return practiceQ();
  if (PS && PS.done) return practiceDone();
  const list = filtered(), stat = q => DB.pstats[q.id];
  return `<div class="page-h"><div><h2>Practice</h2><p>${PRACTICE.length} questions with hints and explanations. Each answer is saved to your progress.</p></div></div>
  <div class="card" style="margin-bottom:14px"><div class="grid g4"><label class="f">Type<select data-chg="pf-type"><option value="">All types</option>${Object.entries(TYPES_P).map(([k, v]) => `<option value="${k}" ${PF.type === k ? 'selected' : ''}>${v}</option>`).join('')}</select></label><label class="f">Topic<select data-chg="pf-topic">${topicOpts(PF.topic)}</select></label><label class="f">Difficulty<select data-chg="pf-d"><option value="">All</option>${['easy', 'medium', 'hard'].map(d => `<option value="${d}" ${PF.d === d ? 'selected' : ''}>${cap(d)}</option>`).join('')}</select></label><div class="row" style="align-items:flex-end"><button class="btn pri" data-act="pr-start" ${list.length ? '' : 'disabled'}>Practice ${list.length}</button><button class="btn" data-act="pr-timed" ${list.length ? '' : 'disabled'}>Timed quiz</button></div></div></div>
  ${list.length ? `<div class="scroll-x"><table class="t"><thead><tr><th>Question</th><th>Type</th><th>Level</th><th>Your record</th></tr></thead><tbody>${list.map(q => { const s = stat(q); return `<tr><td>${esc(q.q.length > 110 ? q.q.slice(0, 108) + '…' : q.q)}</td><td class="small">${TYPES_P[q.type]}</td><td><span class="chip ${q.d === 'easy' ? 'ok' : q.d === 'hard' ? 'bad' : 'warn'}">${q.d}</span></td><td class="small">${s ? `${s.ok}/${s.n} correct` : '<span class="muted">not attempted</span>'}</td></tr>`; }).join('')}</tbody></table></div>` : '<div class="empty">No questions match these filters. Change a filter to see more.</div>'}`;
};
INP['pf-type'] = el => { PF.type = el.value; rerender(); }; INP['pf-topic'] = el => { PF.topic = el.value; rerender(); }; INP['pf-d'] = el => { PF.d = el.value; rerender(); };
ACT['pr-start'] = () => { const qs = filtered(); PS = { qs, i: 0, chosen: null, hint: false, sub: false, ok: 0, t0: Date.now(), log: [] }; rerender(); };
ACT['pr-timed'] = () => { const qs = filtered(); startQuiz({ kind: 'practice', title: 'Practice quiz' + (PF.topic ? ': ' + topicById(PF.topic).t : ''), qs: qs.map(p => ({ id: p.id, q: p.q, o: p.o, a: p.a, e: p.e, topic: p.topic, model: p.model, src: 'Practice bank' })), back: '/practice' }); };
function practiceQ() {
  const q = PS.qs[PS.i]; PS.qt = PS.qt || Date.now();
  return `<div class="page-h"><div><h2>Practice</h2><p>Question ${PS.i + 1} of ${PS.qs.length}</p></div><button class="btn sm" data-act="pr-stop">End session</button></div><div class="bar" style="margin-bottom:14px"><i style="width:${pct(PS.i, PS.qs.length)}%"></i></div>
  <div class="card" style="max-width:820px"><div class="row" style="margin-bottom:8px"><span class="chip">${TYPES_P[q.type]}</span><span class="chip ${q.d === 'easy' ? 'ok' : q.d === 'hard' ? 'bad' : 'warn'}">${q.d}</span><a class="chip" href="#/learn/${q.topic}">${esc(topicById(q.topic).t)}</a></div><h3>${esc(q.q)}</h3>${q.model ? staticSVG(modelOf(q.model)) : ''}
  ${q.o.map((o, i) => `<button class="opt ${PS.sub ? (i === q.a ? 'right' : PS.chosen === i ? 'wrong' : '') : PS.chosen === i ? 'sel' : ''}" data-act="pr-pick" data-i="${i}" ${PS.sub ? 'disabled' : ''}><b>${'ABCD'[i]}</b><span>${esc(o)}</span></button>`).join('')}
  ${PS.hint && !PS.sub ? `<div class="note">Hint: ${esc(q.h)}</div>` : ''}${PS.sub ? `<div class="note ${PS.chosen === q.a ? 'ok' : 'bad'}"><b>${PS.chosen === q.a ? 'Correct.' : 'Not quite.'}</b> ${esc(q.e)}</div>` : ''}
  <div class="row" style="margin-top:10px">${!PS.sub ? `<button class="btn" data-act="pr-hint">Show hint</button><button class="btn pri" data-act="pr-submit" ${PS.chosen == null ? 'disabled' : ''}>Submit answer</button>` : `<button class="btn pri" data-act="pr-next">${PS.i + 1 < PS.qs.length ? 'Next question' : 'Finish'}</button>`}</div></div>`;
}
ACT['pr-pick'] = el => { PS.chosen = +el.dataset.i; rerender(); }; ACT['pr-hint'] = () => { PS.hint = true; rerender(); };
ACT['pr-submit'] = () => { const q = PS.qs[PS.i], ok = PS.chosen === q.a; PS.sub = true; if (ok) PS.ok++; PS.log.push({ id: q.id, ok, topic: q.topic }); recordAnswer(q.id, q.topic, ok, (Date.now() - PS.qt) / 1000); rerender(); };
ACT['pr-next'] = () => { if (PS.i + 1 < PS.qs.length) { PS.i++; PS.chosen = null; PS.hint = false; PS.sub = false; PS.qt = null; } else PS.done = true; rerender(); };
ACT['pr-stop'] = () => { PS.done = true; rerender(); };
function practiceDone() {
  const n = PS.log.length, wrong = [...new Set(PS.log.filter(x => !x.ok).map(x => x.topic))];
  return `<div class="page-h"><div><h2>Session complete</h2></div></div><div class="card" style="max-width:640px"><div class="stat">${PS.ok}/${n}</div><p class="muted">${n ? pct(PS.ok, n) + '% correct' : 'No questions were answered.'}</p>${wrong.length ? `<p><b>Review these topics:</b></p><div class="row">${wrong.map(t => `<a class="btn sm" href="#/learn/${t}">${esc(topicById(t).t)}</a>`).join('')}</div>` : n ? '<div class="note ok">No mistakes this session.</div>' : ''}<div class="row" style="margin-top:14px"><button class="btn pri" data-act="pr-again">Back to practice</button><a class="btn" href="#/progress">See progress</a></div></div>`;
};
ACT['pr-again'] = () => { PS = null; rerender(); };

/* ---------- Quiz engine ---------- */
let QZ = null;
function startQuiz({ kind, title, qs, back, meta }) {
  if (!qs.length) return toast('There are no questions to start.', 'warn');
  QZ = { kind, title, qs, back: back || '/practice', meta: meta || {}, i: 0, ans: qs.map(() => null), qt: qs.map(() => 0), t0: Date.now(), qs0: Date.now(), done: false }; go('/quiz');
}
const qzTick = () => { const a = $('#qz-total'), b = $('#qz-q'); if (!QZ || !a) return; a.textContent = fmtT((Date.now() - QZ.t0) / 1000); b.textContent = fmtT(QZ.qt[QZ.i] + (Date.now() - QZ.qs0) / 1000); };
function qzLeave() { if (QZ) { QZ.qt[QZ.i] += (Date.now() - QZ.qs0) / 1000; QZ.qs0 = Date.now(); } }
VIEWS.quiz = () => {
  if (!QZ || QZ.done) return `<div class="empty">No quiz is running. <a href="#/practice">Go to Practice</a> or <a href="#/ai-quiz">start an AI quiz</a>.</div>`;
  const q = QZ.qs[QZ.i], sel = QZ.ans[QZ.i], iv = setInterval(qzTick, 1000); CLEAN = () => clearInterval(iv);
  const badge = QZ.kind === 'ai' ? '<span class="chip warn">AI-generated practice question · not a previous-year question</span>' : QZ.kind === 'cq' ? `<span class="chip info">${esc(q.src || '')}</span>` : `<span class="chip">${esc(q.src || 'Practice bank')}</span>`;
  return `<div class="page-h"><div><h2>${esc(QZ.title)}</h2><p>Question ${QZ.i + 1} of ${QZ.qs.length}</p></div><div class="row"><span class="chip">Total <b id="qz-total">0:00</b></span><span class="chip">This question <b id="qz-q">0:00</b></span><button class="btn sm danger" data-act="qz-quit">Quit</button></div></div>
  <div class="bar" style="margin-bottom:14px"><i style="width:${pct(QZ.ans.filter(x => x != null).length, QZ.qs.length)}%"></i></div>
  <div class="card" style="max-width:820px"><div class="row" style="margin-bottom:8px">${badge}${q.topic && topicById(q.topic) ? `<span class="chip">${esc(topicById(q.topic).t)}</span>` : ''}</div><h3>${esc(q.q)}</h3>${q.model ? staticSVG(modelOf(q.model)) : ''}${q.o.map((o, i) => `<button class="opt ${sel === i ? 'sel' : ''}" data-act="qz-pick" data-i="${i}" aria-pressed="${sel === i}"><b>${'ABCD'[i]}</b><span>${esc(o)}</span></button>`).join('')}
  <div class="row sb" style="margin-top:12px"><div class="row"><button class="btn" data-act="qz-go" data-d="-1" ${QZ.i === 0 ? 'disabled' : ''}>Previous</button><button class="btn" data-act="qz-skip">Skip</button></div><div class="row">${QZ.i + 1 < QZ.qs.length ? `<button class="btn pri" data-act="qz-go" data-d="1">Next</button>` : ''}<button class="btn ${QZ.i + 1 < QZ.qs.length ? '' : 'pri'}" data-act="qz-submit">Submit quiz</button></div></div></div><div class="row" style="margin-top:12px;max-width:820px">${QZ.qs.map((_, i) => `<button class="btn xs ${i === QZ.i ? 'on' : ''}" data-act="qz-jump" data-i="${i}" title="${QZ.ans[i] == null ? 'Unanswered' : 'Answered'}" style="${QZ.ans[i] != null ? 'border-color:var(--ok)' : ''}">${i + 1}</button>`).join('')}</div>`;
};
ACT['qz-pick'] = el => { QZ.ans[QZ.i] = +el.dataset.i; const y = scrollY; rerender(); scrollTo(0, y); };
ACT['qz-go'] = el => { qzLeave(); QZ.i += +el.dataset.d; rerender(); }; ACT['qz-jump'] = el => { qzLeave(); QZ.i = +el.dataset.i; rerender(); };
ACT['qz-skip'] = () => { qzLeave(); QZ.ans[QZ.i] = null; if (QZ.i + 1 < QZ.qs.length) QZ.i++; rerender(); };
ACT['qz-quit'] = async () => { if (await confirmBox('Quit this quiz? Your answers will not be saved.', 'Quit')) { const b = QZ.back; QZ = null; go(b); } };
ACT['qz-submit'] = async () => {
  const un = QZ.ans.filter(x => x == null).length; if (un && !(await confirmBox(`${un} question(s) are unanswered and will count as skipped. Submit?`, 'Submit', false))) return;
  qzLeave(); const total = (Date.now() - QZ.t0) / 1000; let correct = 0, wrong = 0, skipped = 0;
  QZ.qs.forEach((q, i) => { const a = QZ.ans[i]; if (a == null) skipped++; else { const ok = a === q.a; ok ? correct++ : wrong++; recordAnswer(q.id || (QZ.kind + ':' + i), q.topic || 'eer-model', ok, QZ.qt[i]); } });
  const at = { id: uid('at'), ts: Date.now(), kind: QZ.kind, title: QZ.title, name: DB.settings.name, total: QZ.qs.length, correct, wrong, skipped, time: Math.round(total), meta: QZ.meta, back: QZ.back, qs: QZ.qs.map(q => ({ id: q.id || null, q: q.q, o: q.o, a: q.a, e: q.e || '', topic: q.topic || '', src: q.src || '', model: q.model || '' })), ans: QZ.ans.slice(), qt: QZ.qt.map(x => Math.round(x)) };
  DB.attempts.unshift(at); DB.attempts = DB.attempts.slice(0, 60); DB.save('attempts'); QZ.done = true; go('/attempt/' + at.id);
};
window.addEventListener('beforeunload', e => { if (QZ && !QZ.done && QZ.ans.some(x => x != null)) { e.preventDefault(); e.returnValue = ''; } });
const RV = { filter: 'all', open: {}, ai: {} };
VIEWS.attempt = id => {
  const at = DB.attempts.find(a => a.id === id); if (!at) return `<div class="empty">This attempt was not found. It may have been removed. <a href="#/progress">Back to progress</a></div>`;
  const times = at.qt.filter((t, i) => at.ans[i] != null), topics = {};
  at.qs.forEach((q, i) => { const k = q.topic || 'other'; const t = topics[k] = topics[k] || { n: 0, ok: 0 }; if (at.ans[i] != null) { t.n++; if (at.ans[i] === q.a) t.ok++; } });
  const weak = Object.entries(topics).filter(([k, v]) => k !== 'other' && v.n && v.ok / v.n < .6).map(([k]) => k), show = at.qs.map((q, i) => ({ q, i })).filter(x => RV.filter === 'all' || at.ans[x.i] !== x.q.a);
  return `<div class="page-h"><div><a class="small" href="#${at.back || '/practice'}">← Back</a><h2>${esc(at.title)}</h2><p>${new Date(at.ts).toLocaleString()}</p></div><div class="row"><button class="btn pri" data-act="at-retry" data-id="${at.id}">Retry these questions</button></div></div>
  <div class="grid g4"><div class="card"><div class="stat">${at.correct}/${at.total}</div><span class="muted small">score · ${pct(at.correct, at.total)}% accuracy</span></div><div class="card"><div class="stat">${at.wrong} / ${at.skipped}</div><span class="muted small">incorrect / skipped</span></div><div class="card"><div class="stat">${fmtT(at.time)}</div><span class="muted small">total time</span></div><div class="card"><div class="stat">${times.length ? fmtT(times.reduce((a, b) => a + b, 0) / times.length) : '–'}</div><span class="muted small">average per answered · fastest ${times.length ? fmtT(Math.min(...times)) : '–'} · slowest ${times.length ? fmtT(Math.max(...times)) : '–'}</span></div></div>
  ${at.kind === 'ai' ? '<div class="note warn" style="margin-top:12px">These questions were written by AI for practice. They are not GATE or UGC NET questions and may contain mistakes.</div>' : ''}
  <div class="grid g2" style="margin-top:14px"><div class="card"><h3>Topic performance</h3>${Object.keys(topics).length ? `<table class="t"><tbody>${Object.entries(topics).map(([k, v]) => `<tr><td>${k === 'other' ? 'Other' : `<a href="#/learn/${k}">${esc(topicById(k) ? topicById(k).t : k)}</a>`}</td><td>${v.ok}/${v.n}</td><td><div class="bar"><i style="width:${pct(v.ok, v.n)}%"></i></div></td></tr>`).join('')}</tbody></table>` : '<p class="muted">No answered questions.</p>'}</div>
  <div class="card"><h3>What to do next</h3>${weak.length ? `<p>Weak in: ${weak.map(k => `<b>${esc(topicById(k).t)}</b>`).join(', ')}.</p><div class="row">${weak.slice(0, 2).map(k => `<a class="btn sm" href="#/learn/${k}">Learn ${esc(topicById(k).t)}</a><a class="btn sm" href="#/practice/${k}">Practice</a>`).join('')}</div>` : '<div class="note ok">No weak topic in this attempt.</div>'}</div></div>
  <div class="row sb" style="margin:18px 0 8px"><h3 style="margin:0">Review</h3><div class="row"><button class="btn sm ${RV.filter === 'all' ? 'on' : ''}" data-act="rv-f" data-f="all">All</button><button class="btn sm ${RV.filter === 'wrong' ? 'on' : ''}" data-act="rv-f" data-f="wrong">Mistakes and skipped</button></div></div>
  ${show.length ? show.map(({ q, i }) => { const a = at.ans[i], ok = a === q.a; return `<div class="card" style="margin-bottom:10px"><div class="row sb"><b>${i + 1}. ${esc(q.q)}</b><span class="chip ${a == null ? '' : ok ? 'ok' : 'bad'}">${a == null ? 'skipped' : ok ? 'correct' : 'incorrect'} · ${fmtT(at.qt[i] || 0)}</span></div>${q.model && MODEL_SPECS[q.model] ? staticSVG(modelOf(q.model)) : ''}<p class="small" style="margin:8px 0">Your answer: <b>${a == null ? 'none' : esc(q.o[a])}</b> · Correct: <b>${esc(q.o[q.a])}</b></p><button class="btn xs" data-act="rv-sol" data-i="${i}">${RV.open[i] ? 'Hide solution' : 'View solution'}</button>${RV.open[i] ? `<div class="note ok small" style="margin-top:8px">${esc(q.e || 'No explanation was stored for this question.')}</div><button class="btn xs" data-act="rv-ai" data-id="${at.id}" data-i="${i}">Explain with AI</button>${RV.ai[at.id + i] ? `<div class="note small" style="margin-top:8px"><b>AI explanation (not from the source):</b><br>${esc(RV.ai[at.id + i])}</div>` : ''}` : ''}</div>`; }).join('') : '<div class="note ok">Nothing to review here. No mistakes.</div>'}`;
};
ACT['rv-f'] = el => { RV.filter = el.dataset.f; rerender(); };
ACT['rv-sol'] = el => { RV.open[el.dataset.i] = !RV.open[el.dataset.i]; const y = scrollY; rerender(); scrollTo(0, y); };
ACT['at-retry'] = el => { const at = DB.attempts.find(a => a.id === el.dataset.id); if (at) startQuiz({ kind: at.kind, title: at.title + ' (retry)', qs: at.qs, back: at.back, meta: at.meta }); };
ACT['rv-ai'] = async el => {
  const at = DB.attempts.find(a => a.id === el.dataset.id), q = at.qs[+el.dataset.i], key = at.id + el.dataset.i, sample = await getSample(); if (!sample) return toast('AI explanations are not available in this view.', 'warn');
  el.disabled = true; el.textContent = 'Thinking…';
  try { const r = await sample(`Explain briefly (max 120 words) why the correct option is right and the others are wrong. Question: ${q.q}\nOptions: ${q.o.map((o, i) => 'ABCD'[i] + ') ' + o).join(' | ')}\nCorrect: ${'ABCD'[q.a]}\nContext: database design, ER/EER model. If you are not sure, say so.`, { modelTier: 'quick' }); RV.ai[key] = r.text; } catch (e) { toast(aiErr(e), 'error'); }
  rerender();
};

/* ---------- AI quiz ---------- */
const AIS = { busy: false, msg: '', topic: '', diff: 'medium', n: 5, ctl: null };
VIEWS['ai-quiz'] = topic => {
  if (topic && topicById(topic)) AIS.topic = topic;
  MOUNT = async () => { const s = await getSample(); const b = $('#ai-avail'); if (b) b.innerHTML = s ? '' : '<div class="note warn">AI generation is not available in this view (it needs to run inside Claude). You can still take a quiz from the practice bank, which is not AI-generated.</div>'; if (!s) { const g = $('#ai-go'); if (g) g.disabled = true; } };
  return `<div class="page-h"><div><h2>AI Quiz</h2><p>Claude writes new multiple-choice questions for the topic and level you pick. They are practice questions, never presented as real exam questions.</p></div></div><div id="ai-avail"></div>
  <div class="card" style="max-width:720px"><div class="grid g2"><label class="f">Topic<select data-chg="ai-topic">${topicOpts(AIS.topic, 'Mixed EER topics')}</select></label><label class="f">Difficulty<select data-chg="ai-diff">${['easy', 'medium', 'hard', 'mixed'].map(d => `<option value="${d}" ${AIS.diff === d ? 'selected' : ''}>${cap(d)}</option>`).join('')}</select></label><label class="f">Number of questions<select data-chg="ai-n">${[5, 10, 15, 20].map(n => `<option value="${n}" ${AIS.n === n ? 'selected' : ''}>${n}</option>`).join('')}</select></label></div>
  <div class="row" style="margin-top:14px"><button class="btn pri" id="ai-go" data-act="ai-go" ${AIS.busy ? 'disabled' : ''}>${AIS.busy ? 'Generating…' : 'Generate quiz with AI'}</button>${AIS.busy ? '<button class="btn danger" data-act="ai-stop">Stop</button>' : ''}<button class="btn" data-act="ai-bank">Quiz from practice bank (not AI)</button></div>
  ${AIS.msg ? `<div class="note ${AIS.busy ? '' : 'warn'}" style="margin-top:12px">${AIS.busy ? '<span class="spin"></span> ' : ''}${esc(AIS.msg)}</div>` : ''}<p class="xs muted" style="margin-top:12px">Each generation uses your own Claude usage and asks your permission first. AI can make mistakes: check explanations against your notes.</p></div>`;
};
INP['ai-topic'] = el => { AIS.topic = el.value; }; INP['ai-diff'] = el => { AIS.diff = el.value; }; INP['ai-n'] = el => { AIS.n = +el.value; };
ACT['ai-stop'] = () => { if (AIS.ctl) AIS.ctl.abort(); };
ACT['ai-bank'] = () => { const pool = PRACTICE.filter(p => !AIS.topic || p.topic === AIS.topic).filter(p => AIS.diff === 'mixed' || p.d === AIS.diff); const src = pool.length ? pool : PRACTICE; const qs = src.slice().sort(() => Math.random() - .5).slice(0, AIS.n); if (!pool.length) toast('No bank questions match this topic and level, so a mixed set was used.', 'info'); startQuiz({ kind: 'practice', title: 'Practice-bank quiz', qs: qs.map(p => ({ id: p.id, q: p.q, o: p.o, a: p.a, e: p.e, topic: p.topic, model: p.model, src: 'Practice bank' })), back: '/ai-quiz' }); };
ACT['ai-go'] = async () => {
  const sample = await getSample(); if (!sample) return toast('AI generation is not available in this view.', 'warn');
  const tp = AIS.topic && topicById(AIS.topic), ids = TOPICS.slice(0, 27).map(t => t.id).join(', ');
  const prompt = `You write multiple-choice practice questions for students learning database design, focusing on the ER and Enhanced ER (EER) model.\nTopic: ${tp ? tp.t + ' (' + tp.what + ')' : 'mixed EER topics: generalization, specialization, superclass/subclass, ISA, inheritance, disjoint/overlapping, total/partial, and mapping EER to relational tables'}.\nDifficulty: ${AIS.diff}. Write exactly ${AIS.n} questions.\nRules: exactly 4 options per question and exactly one correct option; be factually correct and consistent with the Elmasri & Navathe notation (circle with d or o, double line = total, single line = partial); vary which option is correct; do NOT say or imply that any question comes from GATE, UGC NET or any past exam; explanation is 1 to 3 sentences.\nReply with ONLY a JSON array: [{"q":"...","options":["...","...","...","..."],"answer":0,"explanation":"...","topic":"<one of: ${ids}>"}]`;
  AIS.busy = true; AIS.msg = 'Thinking… (you may be asked to allow this request)'; AIS.ctl = new AbortController(); rerender();
  try {
    const data = await sample.json(prompt, { signal: AIS.ctl.signal, onText: ({ text }) => { AIS.msg = `Writing questions… ${text.length} characters so far`; const n = $('.note'); if (n && AIS.busy) n.innerHTML = '<span class="spin"></span> ' + esc(AIS.msg); } });
    const ok = (Array.isArray(data) ? data : []).filter(x => x && typeof x.q === 'string' && Array.isArray(x.options) && x.options.length === 4 && x.options.every(o => typeof o === 'string') && Number.isInteger(x.answer) && x.answer >= 0 && x.answer < 4).slice(0, AIS.n);
    if (!ok.length) throw { code: 'invalid_json', message: 'No valid questions in the reply.' };
    const qs = ok.map((x, i) => ({ id: 'ai:' + uid('q'), q: x.q, o: x.options, a: x.answer, e: String(x.explanation || ''), topic: topicById(x.topic) ? x.topic : (AIS.topic || 'eer-model'), src: 'AI-generated' }));
    AIS.busy = false; AIS.msg = ''; if (ok.length < AIS.n) toast(`Only ${ok.length} of ${AIS.n} valid questions came back.`, 'warn', 6000);
    startQuiz({ kind: 'ai', title: 'AI quiz' + (tp ? ': ' + tp.t : ''), qs, meta: { topic: AIS.topic, diff: AIS.diff }, back: '/ai-quiz' });
  } catch (e) { AIS.busy = false; AIS.msg = e && e.code === 'cancelled' ? 'Stopped.' : aiErr(e); rerender(); }
  AIS.ctl = null;
};

/* ---------- Competitive ---------- */
const CF = { exam: '', year: '', topic: '', d: '' };
const cqFiltered = () => DB.cq.filter(q => (!CF.exam || q.exam === CF.exam) && (!CF.year || String(q.year) === CF.year) && (!CF.topic || q.topic === CF.topic) && (!CF.d || q.d === CF.d));
VIEWS.competitive = () => {
  const list = cqFiltered(), years = [...new Set(DB.cq.map(q => q.year))].sort((a, b) => b - a);
  return `<div class="page-h"><div><h2>Competitive Questions</h2><p>GATE and UGC NET questions that someone added and marked as verified. This app never writes or guesses exam questions. AI-generated questions stay in the AI Quiz.</p></div>${DB.settings.editor ? '<a class="btn" href="#/admin/competitive">Add questions</a>' : ''}</div>
  ${DB.cq.length ? `<div class="card" style="margin-bottom:14px"><div class="grid g4"><label class="f">Exam<select data-chg="cf-exam"><option value="">All</option><option ${CF.exam === 'GATE' ? 'selected' : ''}>GATE</option><option ${CF.exam === 'UGC NET' ? 'selected' : ''}>UGC NET</option></select></label><label class="f">Year<select data-chg="cf-year"><option value="">All</option>${years.map(y => `<option ${CF.year === String(y) ? 'selected' : ''}>${y}</option>`).join('')}</select></label><label class="f">Topic<select data-chg="cf-topic">${topicOpts(CF.topic)}</select></label><label class="f">Difficulty<select data-chg="cf-d"><option value="">All</option>${['easy', 'medium', 'hard'].map(d => `<option value="${d}" ${CF.d === d ? 'selected' : ''}>${cap(d)}</option>`).join('')}</select></label></div><div class="row" style="margin-top:10px"><button class="btn pri" data-act="cq-start" ${list.length ? '' : 'disabled'}>Start timed set (${list.length})</button></div></div>
  ${list.map(q => `<div class="card" style="margin-bottom:10px"><div class="row"><span class="chip info">${esc(q.exam)} ${esc(q.year)}</span><span class="chip">${esc(topicById(q.topic) ? topicById(q.topic).t : q.topic)}</span><span class="chip ${q.d === 'easy' ? 'ok' : q.d === 'hard' ? 'bad' : 'warn'}">${q.d}</span><span class="chip ok">verified by uploader</span></div><p style="margin:8px 0 4px">${esc(q.q)}</p><p class="xs muted" style="margin:0">Source: ${esc(q.source)}</p></div>`).join('') || '<div class="empty">No questions match these filters.</div>'}`
    : `<div class="empty"><h3>No verified questions yet</h3><p>Nothing has been added, so nothing is shown. Real previous-year questions come from the official papers, and only questions that were checked against them belong here.</p>${DB.settings.editor ? '<a class="btn pri" href="#/admin/competitive">Add a verified question</a>' : '<p class="small">Turn on editor mode in Settings to add questions.</p>'}<p class="small">Meanwhile, use <a href="#/practice">Practice</a> or the <a href="#/ai-quiz">AI Quiz</a>.</p></div>`}`;
};
INP['cf-exam'] = el => { CF.exam = el.value; rerender(); }; INP['cf-year'] = el => { CF.year = el.value; rerender(); }; INP['cf-topic'] = el => { CF.topic = el.value; rerender(); }; INP['cf-d'] = el => { CF.d = el.value; rerender(); };
ACT['cq-start'] = () => startQuiz({ kind: 'cq', title: 'Competitive set' + (CF.exam ? ': ' + CF.exam : ''), qs: cqFiltered().map(q => ({ id: 'cq:' + q.id, q: q.q, o: q.o, a: q.a, e: q.sol || '', topic: q.topic, src: `${q.exam} ${q.year} · ${q.source}` })), back: '/competitive' });

/* ---------- Progress ---------- */
function topicStats() { return Object.entries(DB.tagg).filter(([k]) => topicById(k)).map(([k, v]) => ({ id: k, n: v.n, ok: v.ok, a: acc(v.n, v.ok), wrong: v.n - v.ok })).sort((x, y) => x.a - y.a); }
const isWeak = s => s.n >= 3 && s.a < 60 && s.wrong >= 2;
VIEWS.progress = () => {
  const done = TOPICS.filter(t => DB.progress[t.id] === 'dn').length, ts = topicStats(), weak = ts.filter(isWeak), A = DB.attempts, tot = ts.reduce((a, s) => a + s.n, 0), ok = ts.reduce((a, s) => a + s.ok, 0), last = A.slice(0, 10).reverse();
  const tm = ts.reduce((a, s) => a + (DB.tagg[s.id].t || 0), 0);
  const chart = last.length ? `<svg viewBox="0 0 ${last.length * 40 + 20} 130" style="width:100%;max-width:520px" role="img" aria-label="Accuracy of last quizzes">${last.map((a, i) => { const h = pct(a.correct, a.total) * 0.9; return `<rect x="${i * 40 + 14}" y="${105 - h}" width="26" height="${h}" rx="4" style="fill:var(--accent)"/><text x="${i * 40 + 27}" y="${100 - h}" text-anchor="middle" style="fill:var(--muted);font-size:10px">${pct(a.correct, a.total)}</text>`; }).join('')}<line x1="8" y1="105" x2="${last.length * 40 + 14}" y2="105" style="stroke:var(--line2)"/></svg>` : '<div class="empty">Take a quiz to see your trend.</div>';
  return `<div class="page-h"><div><h2>Progress</h2><p>Everything here is computed from what you did in this browser.</p></div></div>
  <div class="grid g4"><div class="card"><div class="stat">${done}/${TOPICS.length}</div><span class="muted small">topics completed</span><div class="bar" style="margin-top:8px"><i style="width:${pct(done, TOPICS.length)}%"></i></div></div><div class="card"><div class="stat">${A.length}</div><span class="muted small">quizzes taken</span></div><div class="card"><div class="stat">${tot ? pct(ok, tot) + '%' : '–'}</div><span class="muted small">accuracy over ${tot} answers</span></div><div class="card"><div class="stat">${tot && tm ? fmtT(tm / tot) : '–'}</div><span class="muted small">average time per timed answer</span></div></div>
  <h3 style="margin-top:20px">Weak topics</h3>${weak.length ? `<div class="grid ga">${weak.map(s => `<div class="card" style="border-color:rgba(255,111,145,.5)"><b>${esc(topicById(s.id).t)}</b><p class="small muted" style="margin:4px 0">${s.ok}/${s.n} correct (${s.a}%) · ${s.wrong} mistakes</p><div class="row"><a class="btn xs" href="#/learn/${s.id}">Revise</a><a class="btn xs" href="#/examples">Examples</a><a class="btn xs" href="#/practice/${s.id}">Practice</a><a class="btn xs" href="#/ai-quiz/${s.id}">AI quiz</a></div></div>`).join('')}</div><p class="xs muted">A topic is flagged when you have answered at least 3 questions, made at least 2 mistakes, and scored under 60%.</p>` : `<div class="empty">${tot ? 'No weak topics right now. Keep going.' : 'No answers recorded yet. Try a mini quiz or Practice.'}</div>`}
  <div class="grid g2" style="margin-top:20px"><div class="card"><h3>Topic accuracy</h3>${ts.length ? `<table class="t"><tbody>${ts.map(s => `<tr><td><a href="#/learn/${s.id}">${esc(topicById(s.id).t)}</a></td><td>${s.ok}/${s.n}</td><td style="width:38%"><div class="bar"><i style="width:${s.a}%"></i></div></td><td><span class="chip ${isWeak(s) ? 'bad' : s.a >= 80 && s.n >= 3 ? 'ok' : 'warn'}">${isWeak(s) ? 'weak' : s.a >= 80 && s.n >= 3 ? 'strong' : 'developing'}</span></td></tr>`).join('')}</tbody></table>` : '<p class="muted">Nothing yet.</p>'}</div><div class="card"><h3>Recent quiz accuracy (%)</h3>${chart}</div></div>
  <h3 style="margin-top:20px">Quiz history</h3>${A.length ? `<div class="scroll-x"><table class="t"><thead><tr><th>When</th><th>Quiz</th><th>Type</th><th>Score</th><th>Time</th><th></th></tr></thead><tbody>${A.map(a => `<tr><td class="small">${new Date(a.ts).toLocaleDateString()}</td><td>${esc(a.title)}</td><td><span class="chip">${a.kind === 'ai' ? 'AI-generated' : a.kind === 'cq' ? 'Competitive' : 'Practice'}</span></td><td>${a.correct}/${a.total}</td><td>${fmtT(a.time)}</td><td><a class="btn xs" href="#/attempt/${a.id}">Review</a></td></tr>`).join('')}</tbody></table></div>` : '<div class="empty">No quizzes yet.</div>'}`;
};

/* ---------- Leaderboard ---------- */
const LB = { kind: '', period: '' };
VIEWS.leaderboard = () => {
  const now = Date.now(), per = { week: 7 * 864e5, month: 30 * 864e5 }[LB.period];
  const rows = DB.attempts.filter(a => a.total >= 3 && (!LB.kind || a.kind === LB.kind) && (!per || now - a.ts < per)).map(a => ({ ...a, acc: pct(a.correct, a.total) })).sort((x, y) => y.acc - x.acc || x.time - y.time);
  return `<div class="page-h"><div><h2>Leaderboard</h2><p>Your best quiz attempts on this browser, ranked by accuracy and then by speed.</p></div></div>
  <div class="note warn">This is a personal leaderboard. Ranking against other students would need a shared server and accounts, which this app does not have, so it is not faked here.</div>
  <div class="row" style="margin:12px 0"><label class="f" style="flex-direction:row;align-items:center;gap:6px">Quiz type<select data-chg="lb-kind" style="width:auto"><option value="">All</option><option value="practice" ${LB.kind === 'practice' ? 'selected' : ''}>Practice</option><option value="ai" ${LB.kind === 'ai' ? 'selected' : ''}>AI</option><option value="cq" ${LB.kind === 'cq' ? 'selected' : ''}>Competitive</option></select></label><label class="f" style="flex-direction:row;align-items:center;gap:6px">Period<select data-chg="lb-per" style="width:auto"><option value="">All time</option><option value="month" ${LB.period === 'month' ? 'selected' : ''}>Last 30 days</option><option value="week" ${LB.period === 'week' ? 'selected' : ''}>Last 7 days</option></select></label></div>
  ${rows.length ? `<table class="t"><thead><tr><th>#</th><th>Name</th><th>Quiz</th><th>Accuracy</th><th>Score</th><th>Time</th></tr></thead><tbody>${rows.slice(0, 20).map((a, i) => `<tr><td>${i + 1}</td><td>${esc(a.name)}</td><td><a href="#/attempt/${a.id}">${esc(a.title)}</a></td><td>${a.acc}%</td><td>${a.correct}/${a.total}</td><td>${fmtT(a.time)}</td></tr>`).join('')}</tbody></table><p class="xs muted">Only attempts with at least 3 questions are listed.</p>` : '<div class="empty">No attempts match yet. Complete a quiz of at least 3 questions.</div>'}`;
};
INP['lb-kind'] = el => { LB.kind = el.value; rerender(); }; INP['lb-per'] = el => { LB.period = el.value; rerender(); };

/* ---------- Admin / content manager ---------- */
const AD = { vid: null, cq: null };
const YT = /^(?:https?:\/\/)?(?:www\.|m\.)?(?:youtube\.com\/(?:watch\?(?:.*&)?v=|embed\/|shorts\/)|youtu\.be\/)([A-Za-z0-9_-]{11})(?:[?&#].*)?$/;
VIEWS.admin = sec => {
  if (!DB.settings.editor) return `<div class="empty"><h3>Content manager is off</h3><p>Turn on editor mode in Settings to manage videos, images, resources and competitive questions. This is a convenience toggle, not a security lock.</p><button class="btn pri" data-act="settings">Open settings</button></div>`;
  sec = sec || 'videos'; const secs = [['videos', 'Videos'], ['images', 'Images'], ['resources', 'Resources'], ['competitive', 'Competitive questions'], ['data', 'Backup & reset']];
  const head = `<div class="page-h"><div><h2>Content manager</h2><p>Everything here is stored in this browser only. Export a backup to keep it safe or move it.</p></div></div><div class="tabs">${secs.map(s => `<a href="#/admin/${s[0]}"><button class="${sec === s[0] ? 'on' : ''}" tabindex="-1">${s[1]}</button></a>`).join('')}</div>`;
  const tsel = (id, v) => `<select id="${id}">${topicOpts(v, 'Choose topic')}</select>`;
  if (sec === 'videos') { const v = AD.vid || {}; return head + `<div class="note">Only add YouTube links you have opened and checked. Nothing is pre-filled, so the app never shows a video it has not verified. Thumbnails cannot load in this view, so a play tile is shown.</div><div class="card"><h3>${v.id ? 'Edit' : 'Add'} video</h3><div class="grid g2"><label class="f">Topic${tsel('av-topic', v.topic)}</label><label class="f">Title<input id="av-title" value="${esc(v.title || '')}"></label><label class="f">YouTube URL<input id="av-url" value="${esc(v.url || '')}" placeholder="https://www.youtube.com/watch?v=…"></label><label class="f">Channel<input id="av-ch" value="${esc(v.channel || '')}"></label><label class="f">Duration (optional)<input id="av-dur" value="${esc(v.duration || '')}" placeholder="12:30"></label><label class="f">Description<input id="av-desc" value="${esc(v.desc || '')}"></label></div><div class="row" style="margin-top:10px"><button class="btn pri" data-act="av-save">${v.id ? 'Save changes' : 'Add video'}</button>${v.id ? '<button class="btn" data-act="av-cancel">Cancel</button>' : ''}</div></div><h3 style="margin-top:18px">Videos (${DB.videos.length})</h3>${DB.videos.length ? `<table class="t"><tbody>${DB.videos.map(x => `<tr><td><b>${esc(x.title)}</b><div class="xs muted">${esc(x.channel || '')} · ${esc(topicById(x.topic) ? topicById(x.topic).t : x.topic)}</div></td><td><a href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">link</a></td><td><button class="btn xs" data-act="av-edit" data-id="${x.id}">Edit</button> <button class="btn xs danger" data-act="vid-del" data-id="${x.id}">Delete</button></td></tr>`).join('')}</tbody></table>` : '<div class="empty">No videos yet. Topic pages show "No curated video available yet."</div>'}`; }
  if (sec === 'images') return head + `<div class="card"><h3>Upload learning image</h3><div class="row"><label class="f">Topic${tsel('ai-topic2', '')}</label><button class="btn pri" data-act="ai-img" style="align-self:flex-end">Choose image…</button><input type="file" id="img-file" data-chg="img-file" accept="image/png,image/jpeg,image/webp,image/gif" hidden></div><p class="xs muted">PNG, JPG, WebP or GIF up to 4 MB. Saved in this browser (IndexedDB).</p></div><h3 style="margin-top:18px">All images</h3><div id="adm-gal" class="gal"><span class="muted small">Loading…</span></div>${(MOUNT = async () => { const b = $('#adm-gal'); try { const all = await IDB.all(); b.innerHTML = all.length ? all.map(i => `<figure><img src="${i.data}" alt="${esc(i.title)}"><figcaption><b>${esc(i.title)}</b><div class="xs muted">${esc(topicById(i.topic) ? topicById(i.topic).t : i.topic)}</div><button class="btn xs danger" data-act="adm-imgdel" data-id="${i.id}" style="margin-top:4px">Delete</button></figcaption></figure>`).join('') : '<div class="empty" style="grid-column:1/-1">No images uploaded.</div>'; } catch (e) { b.innerHTML = `<div class="note warn" style="grid-column:1/-1">Image storage is unavailable here (${esc(e.message)}).</div>`; } }, '')}`;
  if (sec === 'resources') return head + `<div class="card"><h3>Add resource</h3><div class="grid g2"><label class="f">Title<input id="ar-title"></label><label class="f">Type<select id="ar-type"><option>Reference book</option><option>Article</option><option>Notes</option><option>Website</option><option>Other</option></select></label><label class="f">Link (optional, https://…)<input id="ar-url"></label><label class="f">Topic${tsel('ar-topic', '')}</label></div><label class="f" style="margin-top:8px">Description<input id="ar-desc"></label><button class="btn pri" data-act="ar-add" style="margin-top:10px">Add resource</button></div><h3 style="margin-top:18px">Resources</h3><table class="t"><tbody>${[...SEED_RESOURCES, ...DB.resources].map(r => `<tr><td><b>${esc(r.title)}</b><div class="xs muted">${esc(r.type)} · ${esc(r.desc || '')}</div></td><td>${r.url ? `<a href="${esc(r.url)}" target="_blank" rel="noopener noreferrer">open</a>` : ''}</td><td>${r.seed ? '<span class="chip">built-in</span>' : `<button class="btn xs danger" data-act="ar-del" data-id="${r.id}">Delete</button>`}</td></tr>`).join('')}</tbody></table>`;
  if (sec === 'competitive') { const c = AD.cq || { o: ['', '', '', ''] }; return head + `<div class="note warn"><b>Only add real questions you have checked against the official paper.</b> The verification box below is required. Nothing is pre-filled by this app.</div><div class="card"><h3>${c.id ? 'Edit' : 'Add'} question</h3><div class="grid g4"><label class="f">Exam<select id="ac-exam"><option ${c.exam === 'GATE' ? 'selected' : ''}>GATE</option><option ${c.exam === 'UGC NET' ? 'selected' : ''}>UGC NET</option></select></label><label class="f">Year<input id="ac-year" type="number" min="1990" max="2100" value="${esc(c.year || '')}"></label><label class="f">Topic${tsel('ac-topic', c.topic)}</label><label class="f">Difficulty<select id="ac-d">${['easy', 'medium', 'hard'].map(d => `<option value="${d}" ${c.d === d ? 'selected' : ''}>${cap(d)}</option>`).join('')}</select></label></div><label class="f" style="margin-top:8px">Question<textarea id="ac-q" rows="3" style="font-family:var(--f-body)">${esc(c.q || '')}</textarea></label><div class="grid g2" style="margin-top:8px">${[0, 1, 2, 3].map(i => `<label class="f">Option ${'ABCD'[i]}<input id="ac-o${i}" value="${esc(c.o[i] || '')}"></label>`).join('')}</div><div class="grid g2" style="margin-top:8px"><label class="f">Correct option<select id="ac-a">${[0, 1, 2, 3].map(i => `<option value="${i}" ${c.a === i ? 'selected' : ''}>${'ABCD'[i]}</option>`).join('')}</select></label><label class="f">Source (paper name / set / question number)<input id="ac-src" value="${esc(c.source || '')}"></label></div><label class="f" style="margin-top:8px">Solution (optional)<textarea id="ac-sol" rows="2" style="font-family:var(--f-body)">${esc(c.sol || '')}</textarea></label><label class="ck" style="margin-top:8px"><input type="checkbox" id="ac-ver"> I checked this question and its answer against the official paper.</label><div class="row" style="margin-top:10px"><button class="btn pri" data-act="ac-save">${c.id ? 'Save changes' : 'Add question'}</button>${c.id ? '<button class="btn" data-act="ac-cancel">Cancel</button>' : ''}</div></div>
  <div class="card" style="margin-top:14px"><h3>Import from JSON</h3><p class="small muted">Array of objects: {"exam","year","topic","d","q","o":[4 strings],"a":0-3,"source","sol"}. Every item is validated and must include a source. Items missing a field are skipped and reported.</p><textarea id="ac-json" rows="4" placeholder='[{"exam":"GATE","year":2000,...}]'></textarea><div class="row" style="margin-top:8px"><button class="btn sm" data-act="ac-import">Import</button><button class="btn sm" data-act="ac-export" ${DB.cq.length ? '' : 'disabled'}>Export all as JSON</button></div></div><h3 style="margin-top:18px">Questions (${DB.cq.length})</h3>${DB.cq.length ? `<table class="t"><tbody>${DB.cq.map(q => `<tr><td><b>${esc(q.exam)} ${esc(q.year)}</b> <span class="xs muted">${esc(q.source)}</span><div class="small">${esc(q.q.slice(0, 120))}${q.q.length > 120 ? '…' : ''}</div></td><td><button class="btn xs" data-act="ac-edit" data-id="${q.id}">Edit</button> <button class="btn xs danger" data-act="ac-del" data-id="${q.id}">Delete</button></td></tr>`).join('')}</tbody></table>` : '<div class="empty">No questions added.</div>'}`; }
  return head + `<div class="grid g2"><div class="card"><h3>Backup</h3><p class="small muted">Saves settings, progress, attempts, videos, resources, competitive questions and notes. Uploaded images are not included.</p><div class="row"><button class="btn pri" data-act="bk-export">Export backup</button><button class="btn" data-act="bk-import">Import backup…</button><input type="file" id="bk-file" data-chg="bk-file" accept=".json,application/json" hidden></div></div><div class="card"><h3>Reset</h3><p class="small muted">Deletes only your learning progress and quiz history. Content you added stays.</p><button class="btn danger" data-act="bk-reset">Reset progress &amp; history</button></div></div>`;
};
ACT['av-cancel'] = () => { AD.vid = null; rerender(); };
ACT['av-edit'] = el => { AD.vid = DB.videos.find(v => v.id === el.dataset.id); rerender(); };
ACT['av-save'] = () => {
  const url = $('#av-url').value.trim(), m = YT.exec(url), topic = $('#av-topic').value, title = $('#av-title').value.trim();
  if (!topic) return toast('Choose a topic.', 'warn'); if (!title) return toast('Enter a title.', 'warn'); if (!m) return toast('That is not a valid YouTube video link. Use a youtube.com/watch?v=… or youtu.be/… link.', 'error');
  const norm = 'https://www.youtube.com/watch?v=' + m[1], rec = { id: (AD.vid && AD.vid.id) || uid('v'), topic, title, url: norm, channel: $('#av-ch').value.trim(), duration: $('#av-dur').value.trim(), desc: $('#av-desc').value.trim() };
  if (AD.vid) DB.videos = DB.videos.map(v => v.id === rec.id ? rec : v); else DB.videos.push(rec); if (DB.save('videos')) toast('Video saved.', 'ok'); AD.vid = null; rerender();
};
ACT['ai-img'] = () => { const t = $('#ai-topic2').value; if (!t) return toast('Choose a topic first.', 'warn'); window.__imgTopic = t; $('#img-file').click(); };
ACT['adm-imgdel'] = async el => { if (!(await confirmBox('Delete this image?', 'Delete'))) return; try { await IDB.del(el.dataset.id); rerender(); } catch (e) { toast('Could not delete: ' + e.message, 'error'); } };
ACT['ar-add'] = () => { const title = $('#ar-title').value.trim(), url = $('#ar-url').value.trim(); if (!title) return toast('Enter a title.', 'warn'); if (url && !/^https?:\/\/\S+$/.test(url)) return toast('The link must start with http:// or https://', 'error'); DB.resources.push({ id: uid('r'), title, type: $('#ar-type').value, url, topic: $('#ar-topic').value, desc: $('#ar-desc').value.trim() }); DB.save('resources'); toast('Resource added.', 'ok'); rerender(); };
ACT['ar-del'] = async el => { if (await confirmBox('Delete this resource?', 'Delete')) { DB.resources = DB.resources.filter(r => r.id !== el.dataset.id); DB.save('resources'); rerender(); } };
ACT['ac-cancel'] = () => { AD.cq = null; rerender(); }; ACT['ac-edit'] = el => { AD.cq = DB.cq.find(q => q.id === el.dataset.id); rerender(); };
ACT['ac-del'] = async el => { if (await confirmBox('Delete this question?', 'Delete')) { DB.cq = DB.cq.filter(q => q.id !== el.dataset.id); DB.save('cq'); rerender(); } };
function cqCheck(x) { const e = []; if (!['GATE', 'UGC NET'].includes(x.exam)) e.push('exam must be GATE or UGC NET'); const y = +x.year; if (!(y >= 1990 && y <= 2100)) e.push('year is invalid'); if (!topicById(x.topic)) e.push('topic is not a valid topic id'); if (!['easy', 'medium', 'hard'].includes(x.d)) e.push('difficulty must be easy, medium or hard'); if (!String(x.q || '').trim()) e.push('question is empty'); if (!Array.isArray(x.o) || x.o.length !== 4 || x.o.some(o => !String(o).trim())) e.push('four non-empty options are required'); if (!(Number.isInteger(x.a) && x.a >= 0 && x.a < 4)) e.push('correct option must be 0-3'); if (!String(x.source || '').trim()) e.push('source is required'); return e; }
ACT['ac-save'] = () => {
  if (!$('#ac-ver').checked) return toast('Tick the verification box: only verified questions may be added.', 'warn');
  const x = { id: (AD.cq && AD.cq.id) || uid('cq'), exam: $('#ac-exam').value, year: +$('#ac-year').value, topic: $('#ac-topic').value, d: $('#ac-d').value, q: $('#ac-q').value.trim(), o: [0, 1, 2, 3].map(i => $('#ac-o' + i).value.trim()), a: +$('#ac-a').value, source: $('#ac-src').value.trim(), sol: $('#ac-sol').value.trim(), added: Date.now() };
  const e = cqCheck(x); if (e.length) return toast('Cannot save: ' + e[0] + '.', 'error');
  if (AD.cq) DB.cq = DB.cq.map(q => q.id === x.id ? x : q); else DB.cq.push(x); DB.save('cq'); AD.cq = null; toast('Question saved.', 'ok'); rerender();
};
ACT['ac-import'] = () => {
  let arr; try { arr = JSON.parse($('#ac-json').value); if (!Array.isArray(arr)) throw 0; } catch (e) { return toast('That is not a valid JSON array.', 'error'); }
  let added = 0; const bad = []; arr.forEach((x, i) => { const e = cqCheck(x || {}); if (e.length) bad.push(`#${i + 1}: ${e[0]}`); else { DB.cq.push({ id: uid('cq'), exam: x.exam, year: +x.year, topic: x.topic, d: x.d, q: String(x.q).trim(), o: x.o.map(String), a: x.a, source: String(x.source), sol: String(x.sol || ''), added: Date.now() }); added++; } });
  DB.save('cq'); toast(`Imported ${added} question(s).` + (bad.length ? ` Skipped ${bad.length}: ${bad.slice(0, 2).join('; ')}` : ''), bad.length ? 'warn' : 'ok', 8000); rerender();
};
ACT['ac-export'] = () => saveFile('competitive-questions.json', JSON.stringify(DB.cq, null, 2));
ACT['bk-export'] = () => saveFile('dbms-lab-backup.json', JSON.stringify({ v: 1, settings: DB.settings, progress: DB.progress, attempts: DB.attempts, pstats: DB.pstats, tagg: DB.tagg, videos: DB.videos, resources: DB.resources, cq: DB.cq, extras: DB.extras }, null, 2));
ACT['bk-import'] = () => $('#bk-file').click();
INP['bk-file'] = el => { const f = el.files[0]; el.value = ''; if (!f) return; const r = new FileReader(); r.onload = async () => { try { const o = JSON.parse(r.result); if (!o || o.v !== 1 || typeof o.progress !== 'object') throw 0; if (!(await confirmBox('Replace your current data with this backup?', 'Import', false))) return; ['progress', 'attempts', 'pstats', 'tagg', 'videos', 'resources', 'cq', 'extras'].forEach(k => { if (o[k] !== undefined) { DB[k] = o[k]; DB.save(k); } }); toast('Backup imported.', 'ok'); rerender(); } catch (e) { toast('This is not a valid backup file.', 'error'); } }; r.onerror = () => toast('Could not read the file.', 'error'); r.readAsText(f); };
ACT['bk-reset'] = async () => { if (await confirmBox('Delete all learning progress, quiz history and answer statistics?', 'Reset')) { DB.progress = {}; DB.attempts = []; DB.pstats = {}; DB.tagg = {}; ['progress', 'attempts', 'pstats', 'tagg'].forEach(k => DB.save(k)); toast('Progress reset.', 'ok'); rerender(); } };

/* ---------- Help ---------- */
VIEWS.help = () => {
  const faq = [['How do I build a generalization?', 'Open the Visualizer, shift-click two or more entities (or press Generalize and tick them). Choose a superclass name and key, tick the common attributes to move up, and set d/o and total/partial.'], ['How do I specialize an entity?', 'Select an entity and press Specialize (or "+ Subclass" in the inspector). Enter subclass names, then add their specific attributes.'], ['How do I read the diagram?', 'The circle is the ISA node. d = disjoint, o = overlapping. A double line to the superclass means total; a single line means partial. The ⊂ mark faces the superclass.'], ['Which mapping option should I choose?', 'Option A always works. B needs a total specialization. C needs disjoint subclasses. D handles overlap. The Schema tab explains any fallback.'], ['How do I convert tables or SQL?', 'Open Table / SQL Import, paste your data or SQL, press Analyze, then confirm or reject each detected item. Only confirmed items are used.'], ['Why does the tool say "possible" or "likely"?', 'Keys and structures are guessed from names and data, which is not proof. You confirm them.'], ['Where is my data stored?', 'Only in this browser (local storage and IndexedDB). Clearing site data removes it. Use Backup & reset to export.'], ['Can I read a diagram from an image?', 'If this view lets the page send images to Claude, the image tab offers it. The result is a suggestion to review. Otherwise the image is a reference.']];
  const lim = ['No accounts or server: the leaderboard is personal to this browser and editor mode is not a security lock.', 'AI quiz and image reading need to run inside Claude and use your own Claude usage.', 'YouTube thumbnails cannot load here, and no videos are pre-filled because none were verified.', 'Competitive questions start empty: real exam questions must be added from official papers.', 'Composite foreign keys, n-ary relationships, categories (union types) and aggregation are not drawn in the Visualizer.', 'The SQL parser reads common CREATE TABLE and ALTER TABLE syntax. Other statements are skipped and listed.'];
  return `<div class="page-h"><div><h2>Help</h2><p>How to use each part, what is stored, and what this app does not do.</p></div></div>
  <div class="grid g2"><div><h3>Common questions</h3>${faq.map(f => `<details class="acc"><summary>${esc(f[0])}</summary><div>${esc(f[1])}</div></details>`).join('')}</div><div><h3>Limits (honest list)</h3><ul class="tight">${lim.map(l => `<li>${esc(l)}</li>`).join('')}</ul><h3 style="margin-top:16px">Keyboard</h3><p class="small"><span class="kbd">/</span> search · <span class="kbd">Ctrl</span>+<span class="kbd">Z</span> undo · <span class="kbd">Delete</span> remove selected in the Visualizer</p><h3 style="margin-top:16px">Resources</h3>${[...SEED_RESOURCES, ...DB.resources].map(r => `<div class="card tight" style="margin-bottom:8px"><b>${r.url ? `<a href="${esc(r.url)}" target="_blank" rel="noopener noreferrer">${esc(r.title)}</a>` : esc(r.title)}</b><div class="xs muted">${esc(r.type)}${r.desc ? ' · ' + esc(r.desc) : ''}</div></div>`).join('')}</div></div>`;
};

/* ---------- Search ---------- */
function searchIndex() {
  const ix = []; TOPICS.forEach(t => ix.push({ k: 'Topic', t: t.t, s: t.what, h: '/learn/' + t.id, x: (t.t + ' ' + t.what + ' ' + (t.terms || []).map(a => a[0]).join(' ')).toLowerCase() }));
  EXAMPLES.forEach(e => ix.push({ k: 'Example', t: e.title, s: e.problem, h: '/examples/' + e.id, x: (e.title + ' ' + e.problem + ' ' + e.tag).toLowerCase() }));
  PRACTICE.forEach(p => ix.push({ k: 'Practice', t: p.q, s: TYPES_P[p.type], h: '/practice/' + p.topic, x: (p.q + ' ' + p.o.join(' ')).toLowerCase() }));
  DB.videos.forEach(v => ix.push({ k: 'Video', t: v.title, s: v.channel || '', h: '/learn/' + v.topic, x: (v.title + ' ' + (v.desc || '')).toLowerCase() }));
  [...SEED_RESOURCES, ...DB.resources].forEach(r => ix.push({ k: 'Resource', t: r.title, s: r.desc || '', h: '/help', x: (r.title + ' ' + (r.desc || '')).toLowerCase() }));
  DB.cq.forEach(q => ix.push({ k: 'Competitive', t: q.q.slice(0, 90), s: q.exam + ' ' + q.year, h: '/competitive', x: q.q.toLowerCase() })); return ix;
}
ACT.search = () => { openModal(`<div class="searchbox"><label class="sr" for="sq">Search</label><input id="sq" type="search" data-inp="sq" placeholder="Search topics, examples, questions…" autocomplete="off"></div><div id="sres" class="res" style="margin-top:10px;max-height:60vh;overflow:auto"><p class="small muted">Type to search. Try "disjoint", "weak entity" or "mapping".</p></div>`); $('#sq').focus(); };
INP.sq = el => {
  const q = el.value.trim().toLowerCase(), box = $('#sres'); if (!q) { box.innerHTML = '<p class="small muted">Type to search.</p>'; return; }
  const toks = q.split(/\s+/), res = searchIndex().map(i => ({ i, sc: toks.every(t => i.x.includes(t)) ? (i.t.toLowerCase().includes(q) ? 3 : 1) : 0 })).filter(r => r.sc).sort((a, b) => b.sc - a.sc).slice(0, 25);
  box.innerHTML = res.length ? res.map(({ i }) => `<a href="#${i.h}" data-act="closemodal"><span class="chip acc">${i.k}</span><span><b>${esc(i.t)}</b><br><span class="small muted">${esc((i.s || '').slice(0, 90))}</span></span></a>`).join('') : `<div class="empty">No results for "${esc(el.value)}".</div>`;
};

/* ---------- Boot ---------- */
function boot() { applyTheme(); renderNav(); window.addEventListener('hashchange', route); route(); }
